using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Persistent.Validation;
using DevExpress.ExpressApp.Security;

namespace GAVELISv2.Module.BusinessObjects
{
    [DefaultClassOptions]
    [DeferredDeletion(false)]
    [CreatableItem(false)]
    [NavigationItem(false)]
    public class DriverPayrollAdjustment : XPObject
    {
        private DriverPayroll2 _DriverPayrollID;
        private string _LineID;
        private Employee _Employee;
        private PayAdjustmentType _AdjustmentType;
        private string _Explanation;
        private decimal _Amount;
        private bool _Include;

        [Custom("AllowEdit", "False")]
        [Association("DriverPayroll2-Adjustments")]
        public DriverPayroll2 DriverPayrollID
        {
            get { return _DriverPayrollID; }
            set
            {
                DriverPayroll2 oldDriverPayrollID = _DriverPayrollID;
                SetPropertyValue("DriverPayrollID", ref _DriverPayrollID, value)
                    ;
                if (!IsLoading && !IsSaving && oldDriverPayrollID != _DriverPayrollID)
                {
                    oldDriverPayrollID = oldDriverPayrollID ?? _DriverPayrollID;
                    oldDriverPayrollID.UpdateAdjustmentsAmt(true);
                }
            }
        }
        [Custom("AllowEdit", "False")]
        public string LineID
        {
            get { return _LineID; }
            set { SetPropertyValue("LineID", ref _LineID, value); }
        }
        [Custom("AllowEdit", "False")]
        public Employee Employee
        {
            get { return _Employee; }
            set { SetPropertyValue("Employee", ref _Employee, value); }
        }
        //[Custom("AllowEdit", "False")]
        [RuleRequiredField("", DefaultContexts.Save)]
        public PayAdjustmentType AdjustmentType
        {
            get { return _AdjustmentType; }
            set
            {
                SetPropertyValue("AdjustmentType", ref _AdjustmentType, value)
                    ;
            }
        }
        //[Custom("AllowEdit", "False")]
        public string Explanation
        {
            get { return _Explanation; }
            set { SetPropertyValue("Explanation", ref _Explanation, value); }
        }
        [Custom("AllowEdit", "False")]
        public bool AutoGenerated
        {
            get { return _AutoGenerated; }
            set { SetPropertyValue("AutoGenerated", ref _AutoGenerated, value); }
        }
        //[Custom("AllowEdit", "False")]
        [Custom("DisplayFormat", "n")]
        public decimal Amount
        {
            get { return _Amount; }
            set
            {
                SetPropertyValue("Amount", ref _Amount, value);
                if (!IsLoading)
                {
                    _DriverPayrollID.UpdateAdjustmentsAmt(true);
                }
            }
        }
        public bool Include
        {
            get { return _Include; }
            set
            {
                SetPropertyValue("Include", ref _Include, value);
                if (!IsLoading)
                {
                    _DriverPayrollID.UpdateAdjustmentsAmt(true);
                }
            }
        }
        [Action(AutoCommit = true, Caption = "Include")]
        public void MarkAsInclude()
        {
            Include = true;
        }

        [Action(AutoCommit = true, Caption = "Not Included")]
        public void UnMarkInclude()
        {
            Include = false;
        }
        public DriverPayrollAdjustment(Session session)
            : base(session)
        {
            // This constructor is used when an object is loaded from a persistent storage.
            // Do not place any code here or place it only when the IsLoading property is false:
            // if (!IsLoading){
            //    It is now OK to place your initialization code here.
            // }
            // or as an alternative, move your initialization code into the AfterConstruction method.
        }
        public override void AfterConstruction()
        {
            base.AfterConstruction();
            // Place here your initialization code.
        }

        #region Get Current User

        private SecurityUser _CurrentUser;
        private bool _AutoGenerated = false;
        [NonPersistent]
        [Custom("AllowEdit", "False")]
        public SecurityUser CurrentUser
        {
            get
            {
                if (SecuritySystem.CurrentUser != null)
                {
                    _CurrentUser = Session.GetObjectByKey<SecurityUser>(
                    Session.GetKeyValue(SecuritySystem.CurrentUser));
                }
                return _CurrentUser;
            }
        }

        #endregion
    }

}
