using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Persistent.Validation;
using DevExpress.ExpressApp.Security;
namespace GAVELISv2.Module.BusinessObjects {
    [DefaultClassOptions]
    [DeferredDeletion(false)]
    [CreatableItem(false)]
    [NavigationItem(false)]
    public class StaffPayrollAdjustment : XPObject {
        private StaffPayroll _StaffPayrollID;
        private string _LineID;
        private Employee _Employee;
        private PayAdjustmentType _AdjustmentType;
        private string _Explanation;
        private decimal _Amount;
        [Custom("AllowEdit", "False")]
        [Association("StaffPayroll-Adjustments")]
        public StaffPayroll StaffPayrollID {
            get { return _StaffPayrollID; }
            set { SetPropertyValue("StaffPayrollID", ref _StaffPayrollID, value)
                ; }
        }
        [Custom("AllowEdit", "False")]
        public string LineID
        {
            get { return _LineID; }
            set { SetPropertyValue("LineID", ref _LineID, value); }
        }
        [Custom("AllowEdit", "False")]
        public Employee Employee {
            get { return _Employee; }
            set { SetPropertyValue("Employee", ref _Employee, value); }
        }
        //[Custom("AllowEdit", "False")]
        [RuleRequiredField("", DefaultContexts.Save)]
        public PayAdjustmentType AdjustmentType {
            get { return _AdjustmentType; }
            set { SetPropertyValue("AdjustmentType", ref _AdjustmentType, value)
                ; }
        }
        //[Custom("AllowEdit", "False")]
        public string Explanation {
            get { return _Explanation; }
            set { SetPropertyValue("Explanation", ref _Explanation, value); }
        }
        [Custom("AllowEdit", "False")]
        public bool AutoGenerated
        {
            get { return _AutoGenerated; }
            set { SetPropertyValue("AutoGenerated", ref _AutoGenerated, value); }
        }
        //[Custom("AllowEdit", "False")]
        [Custom("DisplayFormat", "n")]
        public decimal Amount {
            get { return _Amount; }
            set {
                SetPropertyValue("Amount", ref _Amount, value);
                if (!IsLoading) {
                    _StaffPayrollID.UpdateAdjustmentsAmt(true);}
            }
        }
        public StaffPayrollAdjustment(Session session): base(session) {
            // This constructor is used when an object is loaded from a persistent storage.
            // Do not place any code here or place it only when the IsLoading property is false:
            // if (!IsLoading){
            //    It is now OK to place your initialization code here.
            // }
            // or as an alternative, move your initialization code into the AfterConstruction method.
        }
        public override void AfterConstruction() {
            base.AfterConstruction();
            // Place here your initialization code.
        }

        #region Get Current User

        private SecurityUser _CurrentUser;
        private bool _AutoGenerated = false;
        [NonPersistent]
        [Custom("AllowEdit", "False")]
        public SecurityUser CurrentUser
        {
            get
            {
                if (SecuritySystem.CurrentUser != null)
                {
                    _CurrentUser = Session.GetObjectByKey<SecurityUser>(
                    Session.GetKeyValue(SecuritySystem.CurrentUser));
                }
                return _CurrentUser;
            }
        }

        #endregion

    }
}
